In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Student_Performance_Dataset.csv")

In [2]:
df

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [3]:
'''Find:
1. Total number of students
2. Average marks
3. Highest marks
4. Lowest marks'''

# 1
total_students = len(df)
print("Total Number of students are",total_students)

#2
avg_per = df['Final_Percentage'].mean()
print("Average Percentage of students:",avg_per)

#3 
highest_per = df['Final_Percentage'].max()
print("Highest Percentage of students:",highest_per)

#4
lowest_per = df['Final_Percentage'].min()
print("Lowest Percentage of students:",lowest_per)

Total Number of students are 5000
Average Percentage of students: 67.47765600000001
Highest Percentage of students: 98.33
Lowest Percentage of students: 36.33

In [4]:
# Find the average Final Percentage for each Performance Level.

avg_final_per = df.groupby('Performance_Level')['Final_Percentage'].mean()
avg_final_per

Performance_Level
Average      59.114326
Excellent    85.581518
Good         72.661780
Poor         45.677094
Name: Final_Percentage, dtype: float64

In [8]:
# Find which Performance_Level has the highest average Final Percentage.
higest_performance_level = avg_final_per.idxmax()
higest_performance_level

'Excellent'

In [7]:
# Find how many students are in each Performance_Level.
students = df['Performance_Level'].value_counts()
students

Performance_Level
Good         2191
Average      1951
Excellent     593
Poor          265
Name: count, dtype: int64

In [10]:
# Find the number of students who Passed and Failed.
pass_fail = df['Pass_Fail'].value_counts()
pass_fail

Pass_Fail
Pass    4735
Fail     265
Name: count, dtype: int64

In [12]:
# Find the average Final_Percentage for each Gender.
average_final_percentage = df.groupby('Gender')['Final_Percentage'].mean()
average_final_percentage

Gender
Female    67.419890
Male      67.537924
Name: Final_Percentage, dtype: float64

In [ ]:
# find the average Attendance_Percentage for each Class.
average_attendance_percentage = df.groupby('Class')['Attendance_Percentage'].mean()
average_attendance_percentage

Class
9     75.768473
10    75.295158
11    73.927100
12    74.698934
Name: Attendance_Percentage, dtype: float64

In [17]:
overall_avg_final_percentage = df['Final_Percentage'].mean()
overall_avg_final_percentage

np.float64(67.47765600000001)

In [18]:
# Find all students whose Final_Percentage is greater than the overall average Final_Percentage.
greater_average_final_percentage = df[df['Final_Percentage']>overall_avg_final_percentage]
greater_average_final_percentage

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
5,S0006,19,Male,12,5.2,82,High School,No,Yes,88,70,46,60,68.00,Good,Pass
6,S0007,16,Male,12,0.8,78,High School,No,No,75,69,64,84,69.33,Good,Pass
9,S0010,18,Male,10,5.7,97,High School,Yes,No,72,73,73,61,72.67,Good,Pass
10,S0011,14,Female,9,3.6,88,Graduate,Yes,No,95,85,69,41,83.00,Excellent,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4985,S4986,15,Female,10,1.5,66,High School,Yes,No,68,53,89,76,70.00,Good,Pass
4989,S4990,16,Female,11,2.1,76,Graduate,No,No,56,49,100,51,68.33,Good,Pass
4990,S4991,19,Female,9,4.6,73,High School,Yes,Yes,88,95,98,57,93.67,Excellent,Pass
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [19]:
# find the 5 students with the highest Final_Percentage in your actual dataset.
top_5_students = df.sort_values(by = 'Final_Percentage',ascending = False).head(5)
top_5_students

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
21,S0022,15,Male,12,2.8,83,Postgraduate,No,Yes,100,96,99,86,98.33,Excellent,Pass
3636,S3637,15,Female,9,3.8,90,High School,No,Yes,99,95,99,73,97.67,Excellent,Pass
3748,S3749,17,Male,11,0.5,60,Graduate,No,Yes,99,93,100,58,97.33,Excellent,Pass
2211,S2212,19,Male,11,1.8,87,Graduate,No,Yes,98,98,96,54,97.33,Excellent,Pass
1599,S1600,14,Male,9,5.0,83,High School,Yes,No,100,99,92,71,97.00,Excellent,Pass